pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
        
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
                       
               
            }
        }
	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
    
        sh 'gcloud auth activate-service-account jenkins@mi-dev-lab.iam.gserviceaccount.com --key-file=jenkins.json'
    }
    }
 	 
	stage('Create Instance') {
	 steps {
    
    sh 'gcloud compute instances create webhost3 --zone=us-central1-a --tags=http-server --metadata=startup-script=startup-script.sh'
        
    }
    }
    
    	stage('Collect External IP') {
	 steps {
    
         sh "gcloud compute instances describe webhost3 --zone=us-central1-a --format='get(networkInterfaces[0].accessConfigs[0].natIP)' > ip.txt"
	     sh 'cat ip.txt'
        
    }
    }
    
    
  
    stage('App health check') {
	 steps {

	    sh 'curl http://$(cat ip.txt)'
    
    }
    }
   }
}
